name:  Mbali
title: Mbali's blog
email: 
theme: jekyll-theme-cayman
description: 
logo: ""

author_image: ""
parallax_image_one: "assets/images/pen.jpeg"
parallax_image_two: "assets/images/keyboard.jpeg"
